services:
  - type: web
    name: house-price-predictor
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('punkt')"  # Add if using NLP
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
    plan: free